# Generated by Django 4.0.1 on 2022-12-28 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalusersdb',
            name='code',
            field=models.CharField(blank=True, help_text='Código Único (Usuario+Conexion+BD)', max_length=50, null=True, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='historicalusersdb',
            name='name',
            field=models.CharField(help_text='Nombre de la Base de Datos', max_length=100, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='usersdb',
            name='code',
            field=models.CharField(blank=True, help_text='Código Único (Usuario+Conexion+BD)', max_length=50, null=True, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='usersdb',
            name='name',
            field=models.CharField(help_text='Nombre de la Base de Datos', max_length=100, verbose_name='Nombre'),
        ),
    ]
