# Generated by Django 4.0.1 on 2022-12-28 14:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('manage', '0002_alter_historicalusersdb_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalusersdb',
            name='code',
            field=models.CharField(blank=True, db_index=True, help_text='Código Único (Usuario+Conexion+BD)', max_length=50, null=True, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='usersdb',
            name='code',
            field=models.CharField(blank=True, help_text='Código Único (Usuario+Conexion+BD)', max_length=50, null=True, unique=True, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='usersdb',
            name='user',
            field=models.ForeignKey(help_text='Usuario del Sistema', on_delete=django.db.models.deletion.RESTRICT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
    ]
