# Generated by Django 4.0.1 on 2022-12-29 20:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('manage', '0003_alter_historicalusersdb_code_alter_usersdb_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connectdb',
            name='code',
            field=models.CharField(help_text='Servidor', max_length=50, verbose_name='Host'),
        ),
        migrations.AlterField(
            model_name='connectdb',
            name='dbms',
            field=models.CharField(choices=[('Mysql', 'Mysql'), ('Postgres', 'Postgres'), ('Sqlite', 'Sqlite'), ('Oracle', 'Oracle'), ('SqlServer', 'SqlServer'), ('Otro', 'Otro')], default='Mysql', help_text='Motor de Base de Datos', max_length=50, verbose_name='DBMS'),
        ),
        migrations.AlterField(
            model_name='historicalconnectdb',
            name='code',
            field=models.CharField(help_text='Servidor', max_length=50, verbose_name='Host'),
        ),
        migrations.AlterField(
            model_name='historicalconnectdb',
            name='dbms',
            field=models.CharField(choices=[('Mysql', 'Mysql'), ('Postgres', 'Postgres'), ('Sqlite', 'Sqlite'), ('Oracle', 'Oracle'), ('SqlServer', 'SqlServer'), ('Otro', 'Otro')], default='Mysql', help_text='Motor de Base de Datos', max_length=50, verbose_name='DBMS'),
        ),
        migrations.AlterField(
            model_name='usersdb',
            name='user',
            field=models.ForeignKey(help_text='Usuario del Sistema', on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
    ]
