# Generated by Django 4.0.1 on 2023-03-13 02:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('manage', '0004_alter_connectdb_code_alter_connectdb_dbms_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalusersdb',
            name='code',
            field=models.CharField(db_index=True, default='', help_text='Código Único (Usuario+BD)', max_length=50, verbose_name='Código'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usersdb',
            name='code',
            field=models.CharField(default='', help_text='Código Único (Usuario+BD)', max_length=50, unique=True, verbose_name='Código'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usersdb',
            name='user',
            field=models.ForeignKey(help_text='Usuario del Sistema', on_delete=django.db.models.deletion.RESTRICT, related_name='user', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
    ]
